# These are supported funding model platforms

github: jdnichollsc
patreon: proyecto26
open_collective: proyecto26
ko_fi: proyecto26
tidelift: npm/nativescript-inappbrowser
liberapay: proyecto26
custom: paypal.me/jdnichollsc
